[0.000000] (-) TimerEvent: {}
[0.001302] (object_detector_pkg) JobQueued: {'identifier': 'object_detector_pkg', 'dependencies': OrderedDict()}
[0.002340] (object_detector_pkg) JobStarted: {'identifier': 'object_detector_pkg'}
[0.098901] (-) TimerEvent: {}
[0.199700] (-) TimerEvent: {}
[0.300505] (-) TimerEvent: {}
[0.401397] (-) TimerEvent: {}
[0.502333] (-) TimerEvent: {}
[0.604400] (-) TimerEvent: {}
[0.705662] (-) TimerEvent: {}
[0.806480] (-) TimerEvent: {}
[0.907307] (-) TimerEvent: {}
[1.008118] (-) TimerEvent: {}
[1.108914] (-) TimerEvent: {}
[1.209718] (-) TimerEvent: {}
[1.310602] (-) TimerEvent: {}
[1.411696] (-) TimerEvent: {}
[1.512514] (-) TimerEvent: {}
[1.613296] (-) TimerEvent: {}
[1.714169] (-) TimerEvent: {}
[1.815301] (-) TimerEvent: {}
[1.916171] (-) TimerEvent: {}
[2.016982] (-) TimerEvent: {}
[2.117779] (-) TimerEvent: {}
[2.218636] (-) TimerEvent: {}
[2.319447] (-) TimerEvent: {}
[2.420469] (-) TimerEvent: {}
[2.521648] (-) TimerEvent: {}
[2.622560] (-) TimerEvent: {}
[2.722820] (object_detector_pkg) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.10/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.10/selectors.py", line 469, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.10/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/local/lib/python3.10/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/local/lib/python3.10/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/local/lib/python3.10/dist-packages/colcon_core/task/python/build.py", line 96, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/local/lib/python3.10/dist-packages/colcon_core/task/python/build.py", line 194, in _get_available_commands\n    output = await check_output(\n  File "/usr/local/lib/python3.10/dist-packages/colcon_core/subprocess.py", line 129, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python\', \'-W\', \'ignore:setup.py install is deprecated\', \'-W\', \'ignore:easy_install command is deprecated\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "/root/soarm/object_detector_pkg/setup.py", line 1, in <module>\n    from setuptools import find_packages, setup\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 16, in <module>\n    import setuptools.version\n  File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>\n    import pkg_resources\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>\n    def _initialize_master_working_set():\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside\n    f(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in _build_master\n    ws = cls()\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 557, in __init__\n    self.add_entry(entry)\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 613, in add_entry\n    for dist in find_distributions(entry, True):\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2073, in find_on_path\n    path_item_entries = _by_version_descending(filtered)\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2043, in _by_version_descending\n    return sorted(names, key=_by_version, reverse=True)\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2041, in _by_version\n    return [try_parse(part) for part in parts]\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2041, in <listcomp>\n    return [try_parse(part) for part in parts]\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2031, in try_parse\n    return packaging.version.Version(name)\n  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__\n    raise InvalidVersion(f"Invalid version: \'{version}\'")\nKeyboardInterrupt\n\n'}
[2.725036] (-) TimerEvent: {}
[2.725499] (object_detector_pkg) JobEnded: {'identifier': 'object_detector_pkg', 'rc': 'SIGINT'}
[2.734808] (-) EventReactorShutdown: {}
